### ISSUE TITLE
cplex in maven

### ISSUE THREAD

**Issue by jafarinejad** [vietexob/cplex-optim#1]
I want to use cplex through a maven project. when I use cplex in a non-maven eclipse project, it runs correctly. in non-maven project I had to add the path to native library location of cplex in java build path. but in the maven project, I get errors like "java.lang.NoClassDefFoundError: ilog/concert/IloNumExpr" at runtime. I add dependencies to my cplex.jar in pom :
```
 <dependency>
        <groupId>cplex</groupId>
        <artifactId>cplex</artifactId>
        <version>2.0.1</version>
        <scope>system</scope>
        <systemPath>${basedir}\IBM.ILOG.CPLEX.Optimizer\cplex\lib\cplex.jar</systemPath>
</dependency>
```

and I test to add native libraries to src/main/resources, and adding resource tab in pom: it doesn't work. I add the native library to class path environment variable: it doesn't work. I copy them in c:/windows/system32: it doesn't work!

can you help me? what is the solution? :-(

**Comment by vietexob** [comment]
I have not used Maven or CPLEX in Windows before, so I can't really help with this. My apologies, but it does look like some of the path environments are not correctly set. I also know that CPLEX does not work on Win 32-bit. Finally, hope this video tutorial would be helpful https://youtu.be/oA86HCkCg5k :)

**Comment by vietexob** [comment]
So, here's the solution:
- Add the following dependency to `pom.xml`:
```<dependency>
<groupId>cplex</groupId>
<artifactId>cplex</artifactId>
<version>[your-cplex-version]</version>
</dependency>
```
- Open the terminal and cd to your project directory. Install `cplex.jar` in your maven repo:
`mvn install:install-file -DgroupId=cplex -DartifactId=cplex -Dversion=[your-cplex-version] -Dpackaging=jar -Dfile=[path-to-cplex.jar]`
- If you're using Eclipse, re-initialize the IDE:
`mvn eclipse:eclipse`
- Re-build the project:
`mvn clean package`
- That should resolve the dependency problems. However, in order to run the Java main program, you need to add the following Run Configuration to the VM Arguments (under Arguments):
`-Djava.library.path=/opt/ibm/ILOG/CPLEX_Studioxxx/cplex/bin/x86-64_xxx`
- Replace `[your-cplex-version]`, `[path-to-cplex.jar]` and `xxx` appropriately.
